export const config={api:{bodyParser:{sizeLimit:"10mb"}},maxDuration:60};
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");if(req.method==="OPTIONS")return res.status(200).end();if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});
const{imageBase64,imageUrl,prompt="cinematic smooth motion",style="cinematic"}=req.body||{};
if(!imageBase64&&!imageUrl)return res.status(400).json({error:"imageBase64 or imageUrl required"});
const hfKey=process.env.HF_API_KEY;const errors=[];const fullPrompt=`${prompt}, ${style}, high quality`;
async function hfPost(model,body){return fetch(`https://api-inference.huggingface.co/models/${model}`,{method:"POST",headers:{Authorization:`Bearer ${hfKey}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(55000)});}
if(hfKey){try{const r=await hfPost("stabilityai/stable-video-diffusion-img2vid-xt",{inputs:imageUrl||imageBase64,parameters:{num_frames:14,fps:7,motion_bucket_id:127}});if(r.ok){const ct=r.headers.get("content-type")||"";const buf=await r.arrayBuffer();if(buf.byteLength>1000){const b64=Buffer.from(buf).toString("base64");const mime=ct.includes("gif")?"image/gif":"video/mp4";return res.status(200).json({success:true,videoBase64:`data:${mime};base64,${b64}`,provider:"HuggingFace SVD",type:"video",prompt});}}}catch(e){errors.push(`SVD:${e.message}`);}}
if(hfKey){try{const r=await hfPost("ali-vilab/i2vgen-xl",{inputs:imageUrl||imageBase64,parameters:{prompt:fullPrompt,num_inference_steps:20}});if(r.ok){const ct=r.headers.get("content-type")||"";const buf=await r.arrayBuffer();if(buf.byteLength>1000){const b64=Buffer.from(buf).toString("base64");return res.status(200).json({success:true,videoBase64:`data:video/mp4;base64,${b64}`,provider:"HuggingFace i2vgen-xl",type:"video",prompt});}}}catch(e){errors.push(`i2vgen:${e.message}`);}}
try{const seed=Math.floor(Math.random()*99999);const sm={cinematic:"cinematic camera, dramatic lighting, film",smooth:"gentle motion, soft bokeh, dreamy",dynamic:"dynamic zoom, fast motion","slow-motion":"slow motion, graceful"};const sp=encodeURIComponent(`${prompt}, ${sm[style]||sm.cinematic}, 4k`);const frames=Array.from({length:6},(_,i)=>`https://image.pollinations.ai/prompt/${sp}?model=flux&width=768&height=432&nologo=true&seed=${seed+i*7}&enhance=true`);return res.status(200).json({success:true,frames,videoUrl:frames[0],provider:"Pollinations.ai",type:"frames",prompt,errors});}catch(e){errors.push(`Frames:${e.message}`);}
return res.status(503).json({error:"All providers failed",details:errors});}